name: Deploy via ftp
on: 
  push:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Site
      run: |
        pip install -r requirements.txt
        rm params.json
        mv params.ci.json params.json
        make site
        ls ./_site

    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
        localDir: "./_site"
        remoteDir: "."
        options: "--delete"